### ISSUE TITLE
Game doesn't notify user about loosed guess after 4th warning

### ISSUE THREAD

**Issue by Hozhyi** [dmytrochornyy/Practice#10]
Steps to reproduce:
1. Run the game
2. Press Enter 4 times (as an invalid input)

![image](https://user-images.githubusercontent.com/7387800/102338204-36192e00-3f9c-11eb-9ac1-9b9be3822fff.png)

Actual result: `Oops! That is not a valid letter. You have 0 warnings left:`
Expected result: `Oops! That is not a valid letter. You have no warnings left so you lose one guess:`

**Comment by dmytrochornyy** [comment]
Added new type of message, when there are no warnings left
