### ISSUE TITLE
User doesn't loose any guess after 5th warning

### ISSUE THREAD

**Issue by Hozhyi** [dmytrochornyy/Practice#11]
Steps to reproduce:
1. Run game
2. Loose all warnings and 1 guess
3. Enter 1 letter
4. Enter same letter few more times

![image](https://user-images.githubusercontent.com/7387800/102338766-f43cb780-3f9c-11eb-91ec-53c97a7bc376.png)

Actual result: `Oops! You've already guessed that letter. You now have 0 warnings:` shown many times, no guesses punished
Expected result: `Oops! You've already guessed that letter. You have no warnings left so you lose one guess:` shown and 1 guess is punished each time

**Comment by dmytrochornyy** [comment]
solved: added warning(or guess) subtraction for repeated letter
